branches:
  only:
    - master
dist: bionic
sudo: required
language: python
python:
  - "3.7"
  - "3.6"
services:
  - docker
before_install:
  # Replace docker-compose with the latest version
  - curl -sSL https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
    > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin/docker-compose
install:
  - find requirements -name '*requirements.txt' -exec pip install -r '{}' \;
before_script:
  # Revert alpine sources in dockerfile
  - find docker -name Dockerfile -exec sed -i /mirrors.ustc.edu.cn/d '{}' \;
script:
  - (cd docker/ssrcli && docker-compose up -d --build)
  - (cd tests && ./test.sh)
cache: pip
