dist: bionic
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - (cd tests && ./test.sh)
deploy:
  provider: pypi
  user: "__token__"
  password: ${PYPI_TOKEN}
  on:
    tags: true
cache: pip
