dist: bionic
language: python
python:
  - "3.7"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
script:
  - (cd tests && ./test.sh)
cache: pip
deploy:
  provider: pypi
  user: "__token__"
  password: ${PYPI_TOKEN}
  on:
    tags: true
    skip_existing: true
after_success:
  - (cd tests && codecov)
